const AccountsActionTypes = {
    ACCOUNTS_FETCHING_START:'ACCOUNTS_FETCHING_START',
    ACCOUNTS_FETCHING_SUCCESS:'ACCOUNTS_FETCHING_SUCCESS',
    ACCOUNTS_FETCHING_FAILURE:'ACCOUNTS_FETCHING_FAILURE',
    UPDATE_ACCOUNTS:'UPDATE_ACCOUNTS'
}

export default AccountsActionTypes;