const AccountsActionTypes = {
    ACCOUNTS_FETCHING_START:'ACCOUNTS_FETCHING_START',
    ACCOUNTS_FETCHING_SUCCESS:'ACCOUNTS_FETCHING_SUCCESS',
    ACCOUNTS_FETCHING_FAILURE:'ACCOUNTS_FETCHING_FAILURE',
    ALL_ACCOUNTS_FETCHING_START:'ALL_ACCOUNTS_FETCHING_START',
    ALL_ACCOUNTS_FETCHING_SUCCESS:'ALL_ACCOUNTS_FETCHING_SUCCESS',
    ALL_ACCOUNTS_FETCHING_FAILURE:'ALL_ACCOUNTS_FETCHING_FAILURE',
    UPDATE_ACCOUNTS:'UPDATE_ACCOUNTS',
    SET_ACCOUNTS_MODAL_BODY:'SET_ACCOUNTS_MODAL_BODY',
    SET_SHOW_ACCOUNTS_MODAL:'SET_SHOW_ACCOUNTS_MODAL',
    SET_ACCOUNTS_MODAL_HEADING:'SET_ACCOUNTS_MODAL_HEADING',
    SET_CLOSE_ACCOUNTS_MODAL:'SET_CLOSE_ACCOUNTS_MODAL',
}

export default AccountsActionTypes;