const NotificationsActionTypes = {
    NOTIFICATIONS_FETCHING_START:'NOTIFICATIONS_FETCHING_START',
    NOTIFICATIONS_FETCHING_SUCCESS:'NOTIFICATIONS_FETCHING_SUCCESS',
    NOTIFICATIONS_FETCHING_FAILURE:'NOTIFICATIONS_FETCHING_FAILURE',
    UPDATE_NOTIFICATIONS:'UPDATE_NOTIFICATIONS',
    MARK_NOTIFICATION_AS_READ_START:'MARK_NOTIFICATION_AS_READ_START',
    MARK_NOTIFICATION_AS_READ_SUCCESS:'MARK_NOTIFICATION_AS_READ_SUCCESS',
    MARK_NOTIFICATION_AS_READ_FAILURE:'MARK_NOTIFICATION_AS_READ_START',
} 

export default NotificationsActionTypes;