const CitiesActionTypes = {
    CITIES_FETCHING_START:'CITIES_FETCHING_START',
    CITIES_FETCHING_SUCCESS:'CITIES_FETCHING_SUCCESS',
    CITIES_FETCHING_FAILURE:'CITIES_FETCHING_FAILURE'
}

export default CitiesActionTypes;