const CurrenciesActionTypes = {
    CURRENCIES_FETCHING_START:'CURRENCIES_FETCHING_START',
    CURRENCIES_FETCHING_SUCCESS:'CURRENCIES_FETCHING_SUCCESS',
    CURRENCIES_FETCHING_FAILURE:'CURRENCIES_FETCHING_FAILURE'
}

export default CurrenciesActionTypes;