const BanksActionTypes = {
    BANKS_FETCHING_START:'BANKS_FETCHING_START',
    BANKS_FETCHING_SUCCESS:'BANKS_FETCHING_SUCCESS',
    BANKS_FETCHING_FAILURE:'BANKS_FETCHING_FAILURE',
    UPDATE_BANKS:'UPDATE_BANKS',
}

export default BanksActionTypes;