const AccountTypesActionTypes = {
    ACCOUNT_TYPES_FETCHING_START:'ACCOUNT_TYPES_FETCHING_START',
    ACCOUNT_TYPES_FETCHING_SUCCESS:'ACCOUNT_TYPES_FETCHING_SUCCESS',
    ACCOUNT_TYPES_FETCHING_FAILURE:'ACCOUNT_TYPES_FETCHING_FAILURE',
    UPDATE_ACCOUNT_TYPES:'UPDATE_ACCOUNT_TYPES',
}

export default AccountTypesActionTypes;