const authActionTypes = {
    USER_LOGIN_START : "USER_LOGIN_START",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE : "USER_LOGIN_FAILURE",
    USER_SET_AUTH : "USER_SET_AUTH",
    USER_DESTROY_AUTH : "USER_DESTROY_AUTH",
    APP_FINISHED_LOADING: "APP_FINISHED_LOADING"
}

export default authActionTypes