const AccountEntriesActionTypes = {
    ALL_ACCOUNT_ENTRIES_FETCHING_START:'ALL_ACCOUNT_ENTRIES_FETCHING_START',
    ALL_ACCOUNT_ENTRIES_FETCHING_SUCCESS:'ALL_ACCOUNT_ENTRIES_FETCHING_SUCCESS',
    ALL_ACCOUNT_ENTRIES_FETCHING_FAILURE:'ALL_ACCOUNT_ENTRIES_FETCHING_FAILURE',
}

export default AccountEntriesActionTypes;