const CustomersActionTypes = {
    CUSTOMERS_FETCHING_START:'CUSTOMERS_FETCHING_START',
    CUSTOMERS_FETCHING_SUCCESS:'CUSTOMERS_FETCHING_SUCCESS',
    CUSTOMERS_FETCHING_FAILURE:'CUSTOMERS_FETCHING_FAILURE',
    ALL_CUSTOMERS_FETCHING_START:'ALL_CUSTOMERS_FETCHING_START',
    ALL_CUSTOMERS_FETCHING_SUCCESS:'ALL_CUSTOMERS_FETCHING_SUCCESS',
    ALL_CUSTOMERS_FETCHING_FAILURE:'ALL_CUSTOMERS_FETCHING_FAILURE',
    CUSTOMERS_ADD_CUSTOMER: 'CUSTOMERS_ADD_CUSTOMER',
    CUSTOMERS_ADD_CUSTOMER_ORDER: 'CUSTOMERS_ADD_CUSTOMER_ORDER',
    SET_CUSTOMER_MODAL:'SET_CUSTOMER_MODAL',
    CLOSE_CUSTOMER_MODAL:'CLOSE_CUSTOMER_MODAL',
}

export default CustomersActionTypes;