const CustomersActionTypes = {
    CUSTOMERS_FETCHING_START:'CUSTOMERS_FETCHING_START',
    CUSTOMERS_FETCHING_SUCCESS:'CUSTOMERS_FETCHING_SUCCESS',
    CUSTOMERS_FETCHING_FAILURE:'CUSTOMERS_FETCHING_FAILURE',
    CUSTOMERS_ADD_CUSTOMER: 'CUSTOMERS_ADD_CUSTOMER',
    CUSTOMERS_ADD_CUSTOMER_ORDER: 'CUSTOMERS_ADD_CUSTOMER_ORDER'
}

export default CustomersActionTypes;