const CustomersActionTypes = {
    CUSTOMERS_FETCHING_START:'CUSTOMERS_FETCHING_START',
    CUSTOMERS_FETCHING_SUCCESS:'CUSTOMERS_FETCHING_SUCCESS',
    CUSTOMERS_FETCHING_FAILURE:'CUSTOMERS_FETCHING_FAILURE'
}

export default CustomersActionTypes;