const userActionTypes = {
    USER_FETCHING_START : "USER_FETCHING_START",
    USER_FETCHING_SUCCESS : "USER_FETCHING_SUCCESS",
    USER_FETCHING_FAILURE : "USER_FETCHING_FAILURE",
    DESTROY_USER : "DESTROY_USER",
    
}

export default userActionTypes