const StatusesActionTypes = {
    STATUSES_FETCHING_START:'STATUSES_FETCHING_START',
    STATUSES_FETCHING_SUCCESS:'STATUSES_FETCHING_SUCCESS',
    STATUSES_FETCHING_FAILURE:'STATUSES_FETCHING_FAILURE'
}

export default StatusesActionTypes;