const OrdersActionTypes = {
    CREATE_ORDER:'CREATE_ORDER',
    UPDATE_ORDER:'UPDATE_ORDER',
    DELETE_ORDER:'DELETE_ORDER',
    ORDERS_FETCHING_START:'ORDERS_FETCHING_START',
    ORDERS_FETCHING_SUCCESS:'ORDERS_FETCHING_SUCCESS',
    ORDERS_FETCHING_FAILURE:'ORDERS_FETCHING_FAILURE',
    UPDATE_ORDERS:'UPDATE_ORDERS'
}

export default OrdersActionTypes;