const OrdersActionTypes = {
    CREATE_ORDER:'CREATE_ORDER',
    UPDATE_ORDER:'UPDATE_ORDER',
    DELETE_ORDER:'DELETE_ORDER',
    ORDERS_FETCHING_START:'ORDERS_FETCHING_START',
    ORDERS_FETCHING_SUCCESS:'ORDERS_FETCHING_SUCCESS',
    ORDERS_FETCHING_FAILURE:'ORDERS_FETCHING_FAILURE',
    UPDATE_ORDERS:'UPDATE_ORDERS',
    ORDER_ITEM_ORDER_ENTRIES_FETCHING_START:'ORDER_ITEM_ORDER_ENTRIES_FETCHING_START',
    ORDER_ITEM_ORDER_ENTRIES_FETCHING_SUCCESS:'ORDER_ITEM_ORDER_ENTRIES_FETCHING_SUCCESS',
    ORDER_ITEM_ORDER_ENTRIES_FETCHING_FAILURE:'ORDER_ITEM_ORDER_ENTRIES_FETCHING_FAILURE',
    ORDER_ITEM_LATEST_ORDER_ENTRY_FETCHING_START: 'ORDER_ITEM_LATEST_ORDER_ENTRY_FETCHING_START',
    ORDER_ITEM_LATEST_ORDER_ENTRY_FETCHING_SUCCESS: 'ORDER_ITEM_LATEST_ORDER_ENTRY_FETCHING_SUCCESS',
    ORDER_ITEM_LATEST_ORDER_ENTRY_FETCHING_FAILURE: 'ORDER_ITEM_LATEST_ORDER_ENTRY_FETCHING_FAILURE'
}

export default OrdersActionTypes;