const ImagesActionTypes = {
    IMAGES_FETCHING_START:'IMAGES_FETCHING_START',
    IMAGES_FETCHING_SUCCESS:'IMAGES_FETCHING_SUCCESS',
    IMAGES_FETCHING_FAILURE:'IMAGES_FETCHING_FAILURE',
    UPDATE_IMAGES:'UPDATE_IMAGES',
}

export default ImagesActionTypes;